name: data
on:
  schedule:
    - cron: 0 0 15 * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./src/catalogs.js
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        if: ${{ github.event_name!='schedule' || github.event.schedule == '0 0 15 * *' }}
        uses: githubocto/flat@v3
        with:
          http_url: https://www.ikea.cn/api-host/bff/content/catalogs
          downloaded_filename: data/catalogs.json
          postprocess: ./src/catalogs.js
